### ISSUE TITLE
Too big size of production build

### ISSUE THREAD

**Issue by iksent** [Freemius/pricing-page#2]
The result size of production build's file (freemius-pricing.js) is 2.5Mb.

Why it is so big? This is a size of the average website, but there is only 1 page with several pricing blocks and slider.

I think you should find out why the file is so heavy and try to reduce its' size.

(I am a React-developer, so I know that a lot of React-code can weigh a little in the production build)

**Comment by vovafeldman** [comment]
Hey @iksent, I did a quick look and found out that FontAwesome is entirely compiled with the app, so that's something that can be definitely replaced/optimized. Please note that it will take us some time to get to it.

**Comment by vovafeldman** [comment]
Hey @iksent, kindly try [this branch](https://github.com/Freemius/pricing-page/tree/feature/optimize-performance) optimized for production by our senior ReactJS developer, @xiahengchen, and let me know how it goes (the compiled version should be less than 400Kb now).

**Comment by iksent** [comment]
Hello @vovafeldman, @xiahengchen!

Tried to build "feature/optimize-performance" branch, but got the errors like:

```
ERROR in ./src/components/FreemiusPricingMain.js
Module not found: Error: Can't resolve 'css-loader' in 'C:\Programming\freemius-pricing-page'
 @ ./src/components/FreemiusPricingMain.js 4:0-35
 @ ./src/index.js
```

Due to  "style-loader", "css-loader", "sass-loader" and "file-loader" are not exist in package.json

When I added them to the project by myself, then I got 340kb for `freemius-pricing.js` - this is a good result, I think.

**Comment by xiahengchen** [comment]
Hello @iksent 
We appreciate your feedback. But as you know, when you create your React app, you can see dependencies something like "style-loader", "css-loader" and "file-loader" as default in your node_modules folder. That's why we didn't include these packages in our package.json. Please let me know if you still have any problems on your end. Thanks.

**Comment by iksent** [comment]
My opinion is that when you clone some repository everything should work after `git clone` and `yarn install`.
I see no reason not to add dependencies to your package.json

**Comment by xiahengchen** [comment]
Hello @iksent, We're happy to inform you that we have found the reason why you are facing above issue. The issue was related to `yarn install`. Our team is almost using `npm install`, not `yarn install` and `npm install` is installing all above packages as default what you mentioned. In terms of this issue, we added them to package.json and so you can check the changes on this branch. Thanks for your feedback. :)
