### ISSUE TITLE
Problems with blocks at mobile devices

### ISSUE THREAD

**Issue by iksent** [Freemius/pricing-page#3]
Everything is quite OK at the desktops (all visible) and tablets (horizontal slider):

![2020-09-02_23-23-42](https://user-images.githubusercontent.com/32956521/92021613-7baa4600-ed73-11ea-841f-c3781ff45436.png)

But nothing works on mobile phones: Only one block is visible and "PRO" titles are not clickable:

![2020-09-02_23-24-06](https://user-images.githubusercontent.com/32956521/92021666-89f86200-ed73-11ea-828e-4d1154a0dd2c.png)

**Comment by xiahengchen** [comment]
Hi @iksent, thank you for reporting! But unfortunately, I can't reproduce this issue on my end. Did you use the latest [develop ](https://github.com/Freemius/pricing-page/tree/develop) branch at that time? If not, please checkout that branch again and let me know if you still see this issue. Also, it would be great if you can let me know what mobile devices you used.

**Comment by xiahengchen** [comment]
Hi @iksent, We researched this issue again and found that the issue is related to that you have only one plan. We are showing the packages in a different way when the product has a single plan and there was an issue. We fixed this issue and you can probably checkout [feature/single-plan-on-mobile-show-fix](https://github.com/Freemius/pricing-page/tree/feature/single-plan-on-mobile-show-fix) branch to check the changes. Please let us know if this works for you. Thanks.

**Comment by iksent** [comment]
Hello, @xiahengchen.
Works good now, but I have found some more problems:

1. Freemius badge has z-index larger than the slider's arrow's z-index, so you can't click on arrow at some screen's sizes:

![2020-10-14_09-47-33](https://user-images.githubusercontent.com/32956521/95944819-8e984780-0e02-11eb-85c5-499d0c43babe.png)

2. Pay attention on this layout, it doesn't look good.

![2020-10-14_09-50-11](https://user-images.githubusercontent.com/32956521/95944882-b5ef1480-0e02-11eb-8fa9-204a37416881.png)

3. May be you should avoid using vertical separators at mobile version, because when tarriffs are wraped, it doesn't look good.

![2020-10-14_09-51-06](https://user-images.githubusercontent.com/32956521/95944918-cb643e80-0e02-11eb-9574-f0a09e4f1735.png)

I can suggest you to split the whole tariffs block into single tariffs, so it will look good also when it wraps at the new line:

![2020-10-14_09-55-04](https://user-images.githubusercontent.com/32956521/95945239-72e17100-0e03-11eb-96e9-1ef27b2f4e76.png)

4. The shadow is not full-height:

![2020-10-14_09-52-10](https://user-images.githubusercontent.com/32956521/95944986-f51d6580-0e02-11eb-93f9-654291eda57e.png)

**Comment by xiahengchen** [comment]
@iksent we have fixed all the above issues. Please pull the latest changes from [feature/single-plan-on-mobile-show-fix](https://github.com/Freemius/pricing-page/tree/feature/single-plan-on-mobile-show-fix) branch and then you can see the changes. Please let us know if you have any other problems that we can help with. Thanks.

**Comment by iksent** [comment]
Please pay attention to these problems:

1. 

![2020-10-22_14-05-23](https://user-images.githubusercontent.com/32956521/96850330-1ec43580-1470-11eb-8731-9baefe9649e7.png)

2. Not looking good from "445px" to "468px"
![2020-10-22_14-07-06](https://user-images.githubusercontent.com/32956521/96850354-2552ad00-1470-11eb-901b-4d5c0fc73d31.png)

**Comment by xiahengchen** [comment]
@iksent We fixed the above issues and pushed the changes. Please pull the changes from the [feature/single-plan-on-mobile-show-fix](https://github.com/Freemius/pricing-page/tree/feature/single-plan-on-mobile-show-fix) branch again and let us know if you have any issues. Thanks.

**Comment by iksent** [comment]
And one more bug :)

![2020-11-05_21-50-59](https://user-images.githubusercontent.com/32956521/98270783-07796200-1fb1-11eb-8505-ff678c4ab57b.png)

**Comment by iksent** [comment]
And bug with the slider:

1. Resize window to mobile and click at the last period
![2020-11-05_21-52-38](https://user-images.githubusercontent.com/32956521/98271154-75258e00-1fb1-11eb-9438-61cc83e73694.png)

2. Then resize it back to desktop, you'll get empty space at the right and not working slider control:
![2020-11-05_21-53-04](https://user-images.githubusercontent.com/32956521/98271208-853d6d80-1fb1-11eb-8286-4a86b7eab271.png)

**Comment by iksent** [comment]
Sorry, don't want to open new issue for little bug, can you please fix this also?

![2020-11-05_22-06-47](https://user-images.githubusercontent.com/32956521/98272776-45778580-1fb3-11eb-8e07-b5dc56f6bd96.png)

**Comment by xiahengchen** [comment]
Sorry for the late reply @iksent. We fixed all the bugs you mentioned above. And regarding the right navigation arrow issue, we will remove "**powered by**" promotion tab on the smaller device in the next version of our WP SDK since it is embedded in it. You will see the changes in our next release. Please check the changes and let us know if you see any issues.
branch: [feature/single-plan-on-mobile-show-fix](https://github.com/Freemius/pricing-page/tree/feature/single-plan-on-mobile-show-fix)
![image](https://user-images.githubusercontent.com/67895427/101026078-68e12080-35b1-11eb-8157-c78c8bb3b329.png)
