### ISSUE TITLE
Wrong prices displayed: missing values after "."

### ISSUE THREAD

**Issue by Dudo1985** [Freemius/pricing-page#7]
In the div "fs-selected-pricing-amount" the values after the "." are missing, see screenshoot above 

![immagine](https://user-images.githubusercontent.com/5710734/93618578-c238ab00-f9d7-11ea-9db3-126e2a2af6d6.png)

Right prices are 3.99 and 7.99, as you can see in this second screenshoot

![immagine](https://user-images.githubusercontent.com/5710734/93618353-6c640300-f9d7-11ea-9670-688075e3a8fb.png)

**Comment by xiahengchen** [comment]
Hi @Dudo1985, thank you for reporting! We have fixed the issue that you reported and so you can checkout [feature/pricing-amount-fraction-fix](https://github.com/Freemius/pricing-page/tree/feature/pricing-amount-fraction-fix) branch to check the changes.

**Comment by iksent** [comment]
Hello, @xiahengchen!
I have just checked `pricing-amount-fraction-fix` and it's not working as expected: there are no dots for now, but the prices aren't correct, take a look:

Prev version:
![2020-10-14_10-04-30](https://user-images.githubusercontent.com/32956521/95945867-d5873c80-0e04-11eb-9c03-f3677739fd13.png)
![2020-10-14_10-04-38](https://user-images.githubusercontent.com/32956521/95945872-d7510000-0e04-11eb-8bb6-dd47267e2f74.png)
![2020-10-14_10-04-44](https://user-images.githubusercontent.com/32956521/95945877-d8822d00-0e04-11eb-90e9-e7222d3a6180.png)

And the new version:
![2020-10-14_10-04-54](https://user-images.githubusercontent.com/32956521/95945881-d9b35a00-0e04-11eb-8b27-0a591fa00ff9.png)

PS: And may be we should use dot instead of comma at "Normally ..." text?

![2020-10-14_10-02-54](https://user-images.githubusercontent.com/32956521/95945958-05cedb00-0e05-11eb-9de6-a49936dfb534.png)

**Comment by iksent** [comment]
By the way, don't you think, that we should display price per year, not per month, so users can see the final price instantly without calculations in their heads ;)

Or at least display per month and per year.

**Comment by vovafeldman** [comment]
@iksent the code is intentionally using `num.toLocaleString()` to show the prices based on the local numeric format. Some countries use "." for decimal digits separation, but some use ",". That's btw also the reason we failed to fix the bug on the first try. @xiahengchen is already working on the fix.

With regard to your question, it's psychologically easier to commit when seeing smaller numbers rather than showing the annual price, so this practice is known to increase conversion rate. At a later stage, we may introduce a flag for you to choose if you prefer to show the annual prices.

**Comment by iksent** [comment]
+1 for flag and more configurations :)

**Comment by xiahengchen** [comment]
@iksent Please pull the latest changes of [feature/pricing-amount-fraction-fix](https://github.com/Freemius/pricing-page/tree/feature/pricing-amount-fraction-fix) branch and you can see the bug has been fixed. Please let me know if this works for you.

**Comment by iksent** [comment]
Hello, @xiahengchen!

There is the result of the latest fixes:

![2020-10-22_14-00-20](https://user-images.githubusercontent.com/32956521/96849344-ef60f900-146e-11eb-802b-7b881310362f.png)

I have a special JS-function to display the prices correctly. You can try to use it too:

```
export const toFixedN = (
  number: ?number,
  fractionDigits: number = 4,
  canBeNull: boolean = true,
): string => {
  let num = number

  num = +num
  if (isNaN(num)) {
    return '-'
  }
  if (num === 0) {
    return canBeNull ? '0' : '~0'
  }
  if (num < 1) {
    num = num.toFixed(fractionDigits).replace(/\.?0+$/, '')
  } else {
    num = parseFloat(num.toFixed(fractionDigits))
  }
  return +num === 0 ? `~${num}` : num.toString()
}
```

This function works like standard [toFixed](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed) but also handles small values (<1) correctly.

**Comment by xiahengchen** [comment]
Sorry for the inconvenience @iksent. We fixed the above issue and pushed the changes to the [feature/pricing-amount-fraction-fix](https://github.com/Freemius/pricing-page/tree/feature/pricing-amount-fraction-fix) branch. Please check it and let us know if you still see any issues.

**Comment by vovafeldman** [comment]
Merged to the `develop` branch PR https://github.com/Freemius/pricing-page/pull/9
